mqtt:
  client:
    protocol: $(arg mqtt_protocol)      # MQTTv311
  connection:
    host: $(arg mqtt_host)
    port: $(arg mqtt_port)
    keepalive: $(arg mqtt_keepalive)
  private_path: device/001
serializer: msgpack:dumps
deserializer: msgpack:loads
bridge:
  - factory: mqtt_bridge.bridge:MqttToRosBridge
    msg_type: decenter_msgs.msg:ObjectDetector
    topic_from: /DECENTER/UC2/object-detector
    topic_to: /decenter_fms_manager/object_detector_mqtt_msg