mqtt:
  client:
    protocol: $(arg mqtt_protocol)      # MQTTv311
  connection:
    host: $(arg mqtt_host)
    port: $(arg mqtt_port)
    keepalive: $(arg mqtt_keepalive)
  private_path: device/001
serializer: json:dumps
deserializer: json:loads
bridge:
  - factory: mqtt_bridge.bridge:MqttToRosBridge
    msg_type: decenter_msgs.msg:ObjectDetector
    topic_from: $(arg mqtt_topic)
    topic_to: /decenter_fms_manager/object_detector_mqtt_msg