---
robots:
  - id: $(arg robot_1_id)
    namespace: $(arg robot_1_ns)
    enable_service: $(arg robot_1_enable_service)
  - id: $(arg robot_2_id)
    namespace: $(arg robot_2_ns)
    enable_service: $(arg robot_2_enable_service)
